import type { Manager } from './types';

/**
 * DEMO DATA — invented managers for building and testing the product.
 * Every record has demo: true and is labelled on screen. Replaced by
 * Supabase data (real, researched and claimed profiles) before launch.
 */
export const demoManagers: Manager[] = [
  {
    slug: 'harbourside-hosting', name: 'Harbourside Hosting', initials: 'HH', demo: true,
    tagline: 'Full-service hosting for the Eastern Beaches',
    about: 'A local team of eight looking after apartments and family homes from Bondi to Coogee, with in-person check-ins and our own cleaning crew.',
    cities: ['Sydney'], suburbs: ['Bondi', 'Bronte', 'Tamarama', 'Coogee', 'Clovelly'],
    postcodes: ['2026', '2024', '2034', '2031'],
    propertyCount: 42, avgRating: 4.91, reviewCount: 3120,
    platforms: ['Airbnb', 'Booking.com', 'Stayz'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Check-in', 'Cleaning and linen', 'Maintenance', 'Registration help'],
    feeMin: 15, feeMax: 16, licensedAgent: true, responseHours: 3, claimed: true,
    gated: { setupFee: 250, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 6, noticeDays: 30, ownerStaysAllowed: 'Unlimited, with 14 days notice',
      inclusions: ['Professional photos', 'Pricing reviewed weekly', '24/7 guest support', 'Monthly owner statement'],
      nearbyStats: { withinKm: 2, properties: 12, avgRating: 4.93 } },
  },
  {
    slug: 'eastern-beaches-stays', name: 'Eastern Beaches Stays', initials: 'EB', demo: true,
    tagline: 'Larger portfolio, multi-platform reach',
    about: 'Over 100 properties across the Eastern Suburbs, listed on Airbnb and our own direct-booking site to cut platform fees.',
    cities: ['Sydney'], suburbs: ['Bondi', 'Bondi Junction', 'Randwick', 'Coogee', 'Paddington', 'Double Bay'],
    postcodes: ['2026', '2022', '2031', '2034', '2021', '2028'],
    propertyCount: 118, avgRating: 4.82, reviewCount: 9840,
    platforms: ['Airbnb', 'Direct'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Cleaning and linen', 'Maintenance'],
    feeMin: 18, feeMax: 20, licensedAgent: true, responseHours: 8, claimed: true,
    gated: { setupFee: 0, cleaningPassedOn: true, linenIncluded: false, minTermMonths: 12, noticeDays: 60, ownerStaysAllowed: 'Up to 30 nights a year',
      inclusions: ['Direct-booking website', 'Revenue manager', 'Quarterly property inspection'],
      nearbyStats: { withinKm: 2, properties: 21, avgRating: 4.8 } },
  },
  {
    slug: 'coastline-short-stays', name: 'Coastline Short Stays', initials: 'CS', demo: true,
    tagline: 'Boutique co-hosting, owner stays welcome',
    about: 'Two Superhosts co-hosting a small set of homes. Suited to owners who use their place part of the year.',
    cities: ['Sydney'], suburbs: ['Bondi', 'Bronte', 'Waverley'],
    postcodes: ['2026', '2024'],
    propertyCount: 27, avgRating: 4.97, reviewCount: 1410,
    platforms: ['Airbnb'],
    services: ['Listing setup', 'Dynamic pricing', 'Guest messaging', 'Check-in', 'Styling'],
    feeMin: 14, feeMax: 14, licensedAgent: false, responseHours: 2, claimed: false,
    gated: { setupFee: 400, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 3, noticeDays: 30, ownerStaysAllowed: 'Unlimited',
      inclusions: ['Interior styling consult', 'Welcome packs'],
      nearbyStats: { withinKm: 2, properties: 9, avgRating: 4.97 } },
  },
  {
    slug: 'inner-west-hosts', name: 'Inner West Hosts', initials: 'IW', demo: true,
    tagline: 'Terraces and apartments across the Inner West',
    about: 'Specialists in terraces and small apartments in Newtown, Surry Hills and surrounds.',
    cities: ['Sydney'], suburbs: ['Newtown', 'Surry Hills', 'Darlinghurst', 'Redfern', 'Paddington'],
    postcodes: ['2042', '2010', '2016', '2021'],
    propertyCount: 64, avgRating: 4.85, reviewCount: 4020,
    platforms: ['Airbnb', 'Booking.com'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Cleaning and linen', 'Registration help'],
    feeMin: 16, feeMax: 18, licensedAgent: true, responseHours: 5, claimed: true,
    gated: { setupFee: 300, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 6, noticeDays: 30, ownerStaysAllowed: 'Up to 60 nights a year',
      inclusions: ['NSW register and fire safety help', 'Monthly statement'] },
  },
  {
    slug: 'northern-beaches-holiday-co', name: 'Northern Beaches Holiday Co', initials: 'NB', demo: true,
    tagline: 'Holiday homes from Manly to Palm Beach',
    about: 'Family-run manager of larger holiday homes, listing across all the major holiday platforms.',
    cities: ['Sydney'], suburbs: ['Manly', 'Freshwater', 'Dee Why', 'Avalon', 'Palm Beach'],
    postcodes: ['2095', '2096', '2099', '2107', '2108'],
    propertyCount: 37, avgRating: 4.78, reviewCount: 2210,
    platforms: ['Airbnb', 'Stayz', 'Booking.com', 'Vrbo'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Cleaning and linen', 'Maintenance'],
    feeMin: 17, feeMax: 20, licensedAgent: true, responseHours: 12, claimed: false,
    gated: { setupFee: 500, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 12, noticeDays: 90, ownerStaysAllowed: 'School holidays by arrangement',
      inclusions: ['Pool and garden care arranged', 'Linen hire'] },
  },
  {
    slug: 'southbank-stays', name: 'Southbank Stays', initials: 'SS', demo: true,
    tagline: 'City apartments for business and event travel',
    about: 'We manage apartments across the CBD, Southbank and Docklands, focused on weekday business stays and event peaks.',
    cities: ['Melbourne'], suburbs: ['Melbourne CBD', 'Southbank', 'Docklands', 'South Melbourne'],
    postcodes: ['3000', '3006', '3008', '3205'],
    propertyCount: 88, avgRating: 4.74, reviewCount: 6630,
    platforms: ['Airbnb', 'Booking.com'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Check-in', 'Cleaning and linen'],
    feeMin: 15, feeMax: 17, licensedAgent: true, responseHours: 4, claimed: true,
    gated: { setupFee: 200, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 6, noticeDays: 30, ownerStaysAllowed: 'Up to 30 nights a year',
      inclusions: ['Victorian short-stay levy handled', 'Keyless entry install'] },
  },
  {
    slug: 'bayside-co-hosts', name: 'Bayside Co-Hosts', initials: 'BC', demo: true,
    tagline: 'St Kilda to Brighton, done personally',
    about: 'A small team of co-hosts for apartments and townhouses along the bay.',
    cities: ['Melbourne'], suburbs: ['St Kilda', 'Elwood', 'Albert Park', 'Brighton'],
    postcodes: ['3182', '3184', '3206', '3186'],
    propertyCount: 31, avgRating: 4.92, reviewCount: 1980,
    platforms: ['Airbnb'],
    services: ['Listing setup', 'Dynamic pricing', 'Guest messaging', 'Check-in', 'Cleaning and linen', 'Styling'],
    feeMin: 15, feeMax: 15, licensedAgent: false, responseHours: 3, claimed: true,
    gated: { setupFee: 0, cleaningPassedOn: true, linenIncluded: true, minTermMonths: 3, noticeDays: 30, ownerStaysAllowed: 'Unlimited',
      inclusions: ['No lock-in after 3 months'] },
  },
  {
    slug: 'yarra-short-stays', name: 'Yarra Short Stays', initials: 'YS', demo: true,
    tagline: 'Inner-north and inner-east specialists',
    about: 'Managing homes in Fitzroy, Richmond, South Yarra and Carlton, on every major platform.',
    cities: ['Melbourne'], suburbs: ['Fitzroy', 'Collingwood', 'Richmond', 'South Yarra', 'Carlton'],
    postcodes: ['3065', '3066', '3121', '3141', '3053'],
    propertyCount: 104, avgRating: 4.81, reviewCount: 8120,
    platforms: ['Airbnb', 'Booking.com', 'Stayz', 'Direct'],
    services: ['Listing setup', 'Photography', 'Dynamic pricing', 'Guest messaging', 'Cleaning and linen', 'Maintenance'],
    feeMin: 16, feeMax: 19, licensedAgent: true, responseHours: 6, claimed: true,
    gated: { setupFee: 350, cleaningPassedOn: true, linenIncluded: false, minTermMonths: 12, noticeDays: 60, ownerStaysAllowed: 'Up to 45 nights a year',
      inclusions: ['Direct-booking site', 'Levy and council compliance'] },
  },
];
