import 'server-only';
import { areas } from '@/lib/areas';
import { regionsOf, type Region } from '@/lib/regions';
import { COVER_KM, managersNear } from '@/lib/data';
import { airroi, cached, marketFor, store } from '@/lib/earnings';
import { sendEmail } from '@/lib/email';
import { planOf, plansFor } from '@/lib/pro';
import { RULES } from '@/lib/rules';
import { adminClient } from '@/lib/supabase/server';

/*
 Regional reports: one per region per quarter (with a breakdown by suburb area), built from data we already hold (listing figures, managers, quote activity)
 plus AirROI monthly market figures for seasonality (one call per market per quarter, cached).
 Generated by the daily cron in the first days of each quarter (a few per run), kept forever as history.
 Managers active in the area are emailed; Pro and Enterprise can open them, Free sees what's inside.
 AirROI terms (5.10): aggregated figures only, attributed, for our customers' own use.
*/

const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://www.cohostcompare.com';
const PER_RUN = Number(process.env.REPORTS_PER_RUN || 6);

export type Bucket = { label: string; homes: number; nightly: number | null; revenue: number | null; occupancy: number | null };
export type Month = { month: string; occupancy: number | null; nightly: number | null };
export type Suburb = { label: string; slug: string; homes: number; nightly: number | null; revenue: number | null; occupancy: number | null; rating: number | null; managers: number };
export type ReportData = {
  area: { slug: string; label: string; city: string; lat: number; lng: number; radiusKm: number };
  suburbs?: Suburb[];
  period: string; periodLabel: string; asOf: string | null;
  market: { homes: number; professional: number | null; superhost: number | null; rating: number | null; nightly: number | null; revenue: number | null; occupancy: number | null; buckets: Bucket[] };
  seasonality: Month[] | null;
  managers: { count: number; withFees: number; feeMedian: number | null; feeLow: number | null; feeHigh: number | null; top: { name: string; slug: string; homes: number; rating: number | null }[] };
  owners: { requests90d: number | null; quotedFeeMedian: number | null; quotes: number };
  previous: { period: string; homes: number; nightly: number | null; revenue: number | null } | null;
  rules: { state: string; summary: string } | null;
};

export const periodOf = (d = new Date()) => {
  const syd = new Date(d.toLocaleString('en-US', { timeZone: 'Australia/Sydney' }));
  return `${syd.getFullYear()}-Q${Math.floor(syd.getMonth() / 3) + 1}`;
};
export const periodLabel = (p: string) => {
  const [y, q] = p.split('-Q').map(Number);
  const months = ['January', 'April', 'July', 'October'];
  return `${months[q - 1]} ${y}`;
};

const median = (xs: number[]) => { const s = xs.filter((x) => Number.isFinite(x) && x > 0).sort((a, b) => a - b); if (!s.length) return null; const i = Math.floor(s.length / 2); return s.length % 2 ? s[i] : (s[i - 1] + s[i]) / 2; };
const km = (a: { lat: number; lng: number }, b: { lat: number; lng: number }) => {
  const r = (d: number) => (d * Math.PI) / 180;
  return 6371 * 2 * Math.asin(Math.sqrt(Math.sin(r(b.lat - a.lat) / 2) ** 2 + Math.cos(r(a.lat)) * Math.cos(r(b.lat)) * Math.sin(r(b.lng - a.lng) / 2) ** 2));
};
const occ = (x: unknown) => { const n = Number(x); return n > 1 ? n / 100 : n; };

type L = { listing_id: string; lat: number; lng: number; bedrooms: number | null; ttm_avg_rate: number | null; ttm_revenue: number | null; ttm_occupancy: number | null; rating_overall: number | null; num_reviews: number | null; professional: boolean | null; superhost: boolean | null; fetched_at: string };

async function listingsNear(a: { lat: number; lng: number }, radiusKm: number) {
  const dLat = radiusKm / 111, dLng = radiusKm / (111 * Math.cos((a.lat * Math.PI) / 180));
  const rows: L[] = [];
  for (let from = 0; ; from += 1000) {
    const { data } = await adminClient().from('str_listings').select('listing_id, lat, lng, bedrooms, ttm_avg_rate, ttm_revenue, ttm_occupancy, rating_overall, num_reviews, professional, superhost, fetched_at')
      .gte('lat', a.lat - dLat).lte('lat', a.lat + dLat).gte('lng', a.lng - dLng).lte('lng', a.lng + dLng).range(from, from + 999);
    rows.push(...((data || []) as L[]));
    if (!data || data.length < 1000) break;
  }
  return rows.filter((l) => km(a, l) <= radiusKm);
}

/** Monthly occupancy and nightly rate for the area's AirROI market (cached per quarter). Null if unavailable. */
async function seasonality(a: { slug: string; lat: number; lng: number }, period: string): Promise<Month[] | null> {
  if (process.env.REPORTS_SEASONALITY === '0') return null;
  try {
    const m = await marketFor(a.lat, a.lng);
    if (!m?.country) return null;
    const name = m.full_name || [m.district, m.locality, m.region, m.country].filter(Boolean).join(', ');
    const key = `mm:${period}:${name}`;
    let raw = await cached<unknown>(key);
    if (!raw) {
      const market = Object.fromEntries(Object.entries({ country: m.country, region: m.region, locality: m.locality, district: m.district }).filter(([, v]) => v));
      raw = await airroi('/markets/metrics/all', { method: 'POST', body: JSON.stringify({ market, num_months: 12, currency: 'native' }) });
      await store(key, raw);
    }
    return parseMonthly(raw);
  } catch (e) { console.error('seasonality', a.slug, e); return null; }
}

/** Finds a monthly series in AirROI's response without depending on its exact shape. */
export function parseMonthly(raw: unknown): Month[] | null {
  const arrays: Record<string, unknown>[][] = [];
  const walk = (v: unknown, depth: number) => {
    if (depth > 4 || !v || typeof v !== 'object') return;
    if (Array.isArray(v)) { if (v.length >= 6 && v.every((x) => x && typeof x === 'object' && !Array.isArray(x))) arrays.push(v as Record<string, unknown>[]); v.forEach((x) => walk(x, depth + 1)); return; }
    Object.values(v).forEach((x) => walk(x, depth + 1));
  };
  walk(raw, 0);
  const dateKey = (o: Record<string, unknown>) => Object.keys(o).find((k) => /^(date|month|period|year_month|timestamp)$/i.test(k));
  const pick = (o: Record<string, unknown>, re: RegExp) => { const k = Object.keys(o).find((x) => re.test(x)); if (!k) return null; const v = o[k]; const n = typeof v === 'object' && v ? Number((v as Record<string, unknown>).avg ?? (v as Record<string, unknown>).value ?? (v as Record<string, unknown>).median) : Number(v); return Number.isFinite(n) && n > 0 ? n : null; };
  for (const arr of arrays) {
    if (!dateKey(arr[0])) continue;
    const months = arr.map((o) => ({ month: String(o[dateKey(o)!]).slice(0, 7), occupancy: (() => { const v = pick(o, /^occupancy/i); return v == null ? null : occ(v); })(), nightly: pick(o, /^(adr|average_daily_rate|avg_rate|average_rate)/i) }))
      .filter((x) => /^\d{4}-\d{2}/.test(x.month) && (x.occupancy != null || x.nightly != null))
      .sort((a, b) => a.month.localeCompare(b.month)).slice(-12);
    if (months.length >= 6) return months;
  }
  return null;
}

const areaRadiusKm = (miles: number) => Math.max(3, Math.min(8, miles * 1.609 * 1.3));

export async function buildReport(rg: Region, period = periodOf()): Promise<{ data: ReportData; managerIds: string[] }> {
  const db = adminClient();
  const seen = new Map<string, L>();
  const suburbs: Suburb[] = [];
  const mgrs = new Map<string, { id: string; name: string; slug: string; homes: number; ratingSum: number; ratingW: number; fee: number | null }>();
  for (const a of rg.areas) {
    const ls = await listingsNear(a, areaRadiusKm(a.radiusMiles));
    ls.forEach((l) => seen.set(l.listing_id, l));
    const near = await managersNear(a.lat, a.lng);
    for (const m of near) {
      const t = mgrs.get(m.id) || { id: m.id, name: m.name, slug: m.slug, homes: 0, ratingSum: 0, ratingW: 0, fee: m.feeMin != null ? (Number(m.feeMin) + Number(m.feeMax ?? m.feeMin)) / 2 : null };
      t.homes += m.nearby || 0;
      if (m.nearbyRating && m.nearby) { t.ratingSum += Number(m.nearbyRating) * m.nearby; t.ratingW += m.nearby; }
      mgrs.set(m.id, t);
    }
    suburbs.push({ label: a.label, slug: a.slug, homes: ls.length, nightly: median(ls.map((l) => Number(l.ttm_avg_rate))), revenue: median(ls.map((l) => Number(l.ttm_revenue))), occupancy: median(ls.map((l) => occ(l.ttm_occupancy))), rating: median(ls.filter((l) => Number(l.num_reviews) > 0).map((l) => Number(l.rating_overall))), managers: near.length });
  }
  const ls = [...seen.values()];
  const bucket = (label: string, f: (b: number) => boolean): Bucket => {
    const xs = ls.filter((l) => l.bedrooms != null && f(Number(l.bedrooms)));
    return { label, homes: xs.length, nightly: median(xs.map((l) => Number(l.ttm_avg_rate))), revenue: median(xs.map((l) => Number(l.ttm_revenue))), occupancy: median(xs.map((l) => occ(l.ttm_occupancy))) };
  };
  const managers = [...mgrs.values()].sort((x, y) => y.homes - x.homes);
  const fees = managers.map((m) => m.fee).filter((x): x is number => x != null);

  // Owner activity across the region's areas over the last 90 days (quote_requests lat/lng from 008).
  let requests90d: number | null = 0, quotedFeeMedian: number | null = null, quotes = 0;
  const since = new Date(Date.now() - 90 * 86400e3).toISOString();
  const reqIds = new Set<string>();
  for (const a of rg.areas) {
    const r = areaRadiusKm(a.radiusMiles), dLat = r / 111, dLng = r / (111 * Math.cos((a.lat * Math.PI) / 180));
    const { data: reqs, error } = await db.from('quote_requests').select('id, lat, lng').gte('created_at', since)
      .gte('lat', a.lat - dLat).lte('lat', a.lat + dLat).gte('lng', a.lng - dLng).lte('lng', a.lng + dLng);
    if (error) { requests90d = null; break; }
    (reqs || []).filter((q) => q.lat != null && km(a, q) <= r).forEach((q) => reqIds.add(q.id));
  }
  if (requests90d !== null) {
    requests90d = reqIds.size;
    if (reqIds.size) {
      const { data: qs } = await db.from('quote_request_managers').select('quote').in('request_id', [...reqIds]).not('quote', 'is', null);
      const fs = (qs || []).map((q) => Number((q.quote as { feePct?: number }).feePct)).filter((x) => x > 0);
      quotes = fs.length;
      if (fs.length >= 3) quotedFeeMedian = median(fs); // never fewer than 3, so no single quote can be worked out
    }
  }

  const centre = { slug: rg.slug, lat: rg.areas.reduce((x, a) => x + a.lat, 0) / rg.areas.length, lng: rg.areas.reduce((x, a) => x + a.lng, 0) / rg.areas.length };
  const { data: prev } = await db.from('suburb_reports').select('period, data').eq('area_slug', rg.slug).lt('period', period).order('period', { ascending: false }).limit(1).maybeSingle();
  const pd = prev?.data as ReportData | undefined;
  const rules = RULES.find((r) => r.code === rg.state);
  const asOf = ls.reduce<string | null>((m, l) => (!m || l.fetched_at > m ? l.fetched_at : m), null);

  const data: ReportData = {
    area: { slug: rg.slug, label: rg.label, city: rg.state === 'vic' ? 'Victoria' : 'New South Wales', lat: centre.lat, lng: centre.lng, radiusKm: Math.round(Math.max(...rg.areas.map((a) => areaRadiusKm(a.radiusMiles))) * 10) / 10 },
    suburbs: suburbs.sort((x, y) => y.homes - x.homes),
    period, periodLabel: periodLabel(period), asOf,
    market: {
      homes: ls.length,
      professional: ls.length ? ls.filter((l) => l.professional).length / ls.length : null,
      superhost: ls.length ? ls.filter((l) => l.superhost).length / ls.length : null,
      rating: median(ls.filter((l) => Number(l.num_reviews) > 0).map((l) => Number(l.rating_overall))),
      nightly: median(ls.map((l) => Number(l.ttm_avg_rate))), revenue: median(ls.map((l) => Number(l.ttm_revenue))), occupancy: median(ls.map((l) => occ(l.ttm_occupancy))),
      buckets: [bucket('Studio and 1 bedroom', (b) => b <= 1), bucket('2 bedrooms', (b) => b === 2), bucket('3 bedrooms', (b) => b === 3), bucket('4+ bedrooms', (b) => b >= 4)],
    },
    seasonality: await seasonality(rg.areas.slice().sort((x, y) => (suburbs.find((s) => s.slug === y.slug)?.homes || 0) - (suburbs.find((s) => s.slug === x.slug)?.homes || 0))[0], period),
    managers: {
      count: managers.length, withFees: fees.length, feeMedian: median(fees), feeLow: fees.length ? Math.min(...fees) : null, feeHigh: fees.length ? Math.max(...fees) : null,
      top: managers.filter((m) => m.homes > 0).slice(0, 8).map((m) => ({ name: m.name, slug: m.slug, homes: m.homes, rating: m.ratingW ? m.ratingSum / m.ratingW : null })),
    },
    owners: { requests90d, quotedFeeMedian, quotes },
    previous: pd ? { period: prev!.period, homes: pd.market.homes, nightly: pd.market.nightly, revenue: pd.market.revenue } : null,
    rules: rules ? { state: rules.name, summary: rules.summary } : null,
  };
  return { data, managerIds: managers.map((m) => m.id) };
}

/** Every region we report on (from the areas we hold data for). */
export async function allRegions() { return regionsOf(await areas()); }

/** Generates missing reports for this quarter (a few per run), then emails managers about new ones. */
export async function runReports(limit = PER_RUN) {
  const db = adminClient();
  const period = periodOf();
  const { data: done, error } = await db.from('suburb_reports').select('area_slug').eq('period', period);
  if (error) return { made: 0, notified: 0, note: 'Run SQL 014 first' };
  const have = new Set((done || []).map((r) => r.area_slug));
  const regions = await allRegions();
  const todo = regions.filter((r) => !have.has(r.slug)).slice(0, limit);
  let made = 0;
  for (const rg of todo) {
    try {
      const { data, managerIds } = await buildReport(rg, period);
      if (data.market.homes < 10) { await db.from('suburb_reports').insert({ area_slug: rg.slug, area_label: rg.label, period, data, manager_ids: managerIds, notified_at: new Date().toISOString() }); continue; } // too thin to send
      const { error: e } = await db.from('suburb_reports').insert({ area_slug: rg.slug, area_label: rg.label, period, data, manager_ids: managerIds });
      if (!e) made++;
    } catch (e) { console.error('report', rg.slug, e); }
  }
  const notified = await notifyReports();
  return { made, notified, remaining: Math.max(0, regions.length - have.size - todo.length) };
}

/** Reports a manager can see in their dashboard: their areas plus areas they follow (Enterprise: all). */
export async function reportsFor(managerId: string, follow: string[]) {
  const db = adminClient();
  const plan = planOf((await plansFor([managerId])).get(managerId));
  const cols = 'id, area_slug, area_label, period, created_at, manager_ids';
  const q = plan === 'enterprise'
    ? db.from('suburb_reports').select(cols)
    : follow.length
      ? db.from('suburb_reports').select(cols).or(`manager_ids.cs.{${managerId}},area_slug.in.(${follow.map((f) => `"${f.replace(/"/g, '')}"`).join(',')})`)
      : db.from('suburb_reports').select(cols).contains('manager_ids', [managerId]);
  const { data } = await q.order('period', { ascending: false }).order('area_label').limit(500);
  return { plan, rows: ((data || []) as { id: string; area_slug: string; area_label: string; period: string; created_at: string; manager_ids: string[] }[]) };
}

async function notifyReports() {
  const db = adminClient();
  const { data: fresh } = await db.from('suburb_reports').select('id, area_slug, area_label, period, manager_ids').is('notified_at', null).limit(40);
  if (!fresh?.length) return 0;
  // Group by manager so each person gets one email listing all their new reports.
  const byManager = new Map<string, typeof fresh>();
  for (const r of fresh) for (const id of r.manager_ids || []) byManager.set(id, [...(byManager.get(id) || []), r]);
  const { data: followers } = await db.from('managers').select('id, report_follow').neq('report_follow', '{}');
  for (const f of followers || []) for (const r of fresh) if ((f.report_follow as string[]).includes(r.area_slug) && !(byManager.get(f.id) || []).includes(r)) byManager.set(f.id, [...(byManager.get(f.id) || []), r]);
  const ids = [...byManager.keys()];
  const { data: ms } = ids.length ? await db.from('managers').select('id, name, claimed, report_emails').in('id', ids).eq('claimed', true) : { data: [] };
  const plans = await plansFor((ms || []).map((m) => m.id));
  let sent = 0;
  for (const m of ms || []) {
    if (m.report_emails === false) continue;
    const { data: mem } = await db.from('manager_members').select('user_id').eq('manager_id', m.id);
    const emails = (await Promise.all((mem || []).map(async (x) => (await db.auth.admin.getUserById(x.user_id)).data.user?.email))).filter(Boolean) as string[];
    if (!emails.length) continue;
    const reps = byManager.get(m.id)!;
    const paid = planOf(plans.get(m.id)) !== 'free';
    const list = reps.map((r) => `- ${r.area_label}`).join('\n');
    await sendEmail({
      to: emails,
      subject: `New regional report${reps.length > 1 ? 's' : ''}: ${reps.slice(0, 2).map((r) => r.area_label).join(', ')}${reps.length > 2 ? ` and ${reps.length - 2} more` : ''}`,
      text: paid
        ? `Hi,\n\nThe ${periodLabel(reps[0].period)} regional short-stay report${reps.length > 1 ? 's are' : ' is'} ready for regions where ${m.name} is active:\n\n${list}\n\nEach report covers nightly rates and revenue by bedrooms and by suburb, seasonality, how busy the market is, how manager fees compare and owner activity. Past reports stay in your dashboard.\n\nTo stop these emails, turn off report emails under Alerts in your dashboard.`
        : `Hi,\n\nWe've published the ${periodLabel(reps[0].period)} regional short-stay report${reps.length > 1 ? 's' : ''} for regions where ${m.name} is active:\n\n${list}\n\nThey cover nightly rates and revenue by bedrooms and by suburb, seasonality, how busy the market is, how manager fees compare and owner activity. Regional reports are included in Pro.\n\nTo stop these emails, turn off report emails under Alerts in your dashboard.`,
      cta: { label: paid ? 'Open your reports' : 'See what’s in the reports', url: `${SITE}/dashboard/reports` },
    });
    sent++;
  }
  await db.from('suburb_reports').update({ notified_at: new Date().toISOString() }).in('id', fresh.map((r) => r.id));
  return sent;
}

