// Researched manager businesses, matched to Airbnb host/co-host accounts found in the data sweep.
// `match` = normalised account names (see norm() in cluster.js). Only publicly available business
// information is used. Fees appear only where the business publishes them, with the source.
// Research date: 30 Sep 2026.
export const SEED = [
  // ---------- Sydney ----------
  { slug: 'hometime', name: 'Hometime', match: ['hometime'], website: 'https://www.hometime.io', cities: ['Sydney', 'Melbourne'],
    tagline: 'National full-service short-term rental manager',
    about: 'Full-service short-term rental manager operating across Sydney, Melbourne and Brisbane with a local host model. Named Australia’s Best Short-Term Rental Property Manager at the 2026 STRIVE Awards.',
    fee_note: 'Quote-based', sources: ['https://yourneighbourhood.com.au/the-best-airbnb-management-companies-in-australia/'], published: true },
  { slug: 'labode-accommodation', name: "L'Abode Accommodation", match: ['labodeaccommodation', 'labodeaccommodationspeciali', 'labodeaccommodationspecialists'], website: 'https://labodeaccommodation.com.au', cities: ['Sydney'],
    tagline: 'Short-stay and furnished rental management in Sydney',
    about: 'Sydney manager of short-stay and furnished rentals, in the private rental business for over ten years, with an in-house maintenance team.',
    sources: ['https://labodeaccommodation.com.au/short-term-letting/'], published: true },
  { slug: 'madecomfy', name: 'MadeComfy', match: ['madecomfy'], website: 'https://www.madecomfy.com.au', cities: ['Sydney', 'Melbourne'],
    tagline: 'National full-service manager and Airbnb partner',
    about: 'National full-service short-term rental manager covering guest support, cleaning and linen, dynamic pricing, multi-platform distribution and regulatory setup.',
    fee_min: 15, fee_max: 25, fee_note: '15–25% of booking revenue (published range)',
    sources: ['https://blog.madecomfy.com.au/blog/best-short-term-rental-channel-manager-in-australia'], published: true },
  { slug: 'hotelesque', name: 'Hotelesque', match: ['hotelesque'], website: null, cities: ['Sydney'],
    tagline: 'Short-stay management around Bondi Beach', about: 'Short-term rental manager with homes around Bondi Beach.', published: true },
  { slug: 'holidays-by-etch', name: 'Holidays by Etch', match: ['holidaysbyetch'], website: 'https://www.etchrealestate.com.au/holidays-by-etch/', cities: ['Sydney'],
    tagline: 'Short-term management from Etch Real Estate', licensed_agent: true,
    about: 'Short-term property management arm of Etch Real Estate on Sydney’s Northern Beaches.', sources: ['https://www.etchrealestate.com.au/holidays-by-etch/'], published: true },
  { slug: 'bidnstay', name: 'BidnStay', match: ['benfrombidnstay', 'bidnstay'], website: 'https://bidnstay.au', cities: ['Sydney'],
    tagline: 'Short-term property management in Sydney', about: 'Sydney short-term rental property manager.', published: true },
  { slug: 'wonder-view-stays', name: 'Wonder View Stays', match: ['wonderviewstays'], website: 'http://wonderview.au', cities: ['Sydney'],
    tagline: 'Short-stay management around Manly', about: 'Short-term rental manager with homes around Manly and Pyrmont.', published: true },
  { slug: 'short-term-accommodation-management', name: 'Short Term Accommodation Management', match: ['shorttermaccommodationmanage', 'shorttermaccommodationmanagement'], website: 'https://www.stam.au', cities: ['Sydney', 'Melbourne'],
    tagline: 'Short-stay management in Sydney, Melbourne and Brisbane', about: 'Short-term rental manager with offices in Sydney, Melbourne and Brisbane.', sources: ['https://www.stam.au/'], published: true },
  { slug: 'the-apartment-service', name: 'The Apartment Service', match: ['theapartmentservice'], website: 'https://apartmentservice.com.au', cities: ['Sydney'],
    tagline: 'Furnished and short-stay apartments in Sydney', about: 'Sydney operator of furnished and short-stay apartments.', published: true },
  { slug: 'sydney-dreams', name: 'Sydney Dreams', match: ['dreams'], website: 'https://sydneydreams.com.au/propertymanagement/', cities: ['Sydney'],
    tagline: 'Holiday rental apartments and property management', about: 'Holiday rental apartment operator offering property management to owners.', published: true },
  { slug: 'bondi-beach-holiday-homes', name: 'Bondi Beach Holiday Homes', match: ['bondibeachholidayhomes'], website: 'https://bondibeachholidayhomes.com', cities: ['Sydney'],
    tagline: 'Holiday homes around Bondi Beach', about: 'Holiday home manager around Bondi Beach that takes on owners’ homes.', sources: ['https://www.bondibeachholidayhomes.com/list-your-home'], published: true },
  { slug: 'alexi-stays', name: 'Alexi Stays', match: ['alexistays'], website: null, cities: ['Sydney'],
    tagline: 'Short-stay management in Sydney', about: 'Short-term rental manager with homes across Sydney, including Newtown.', published: true },
  { slug: 'guest-realty', name: 'Guest Realty', match: ['guestrealty'], website: 'https://www.guestrealty.co', cities: ['Sydney'],
    tagline: 'Short-term rental management in Sydney', about: 'Sydney short-term rental manager.', published: true },
  { slug: 'squirrel-manager', name: 'Squirrel Manager', match: ['squirrelmanager'], website: null, cities: ['Sydney'],
    tagline: 'Short-stay management in Sydney', about: 'Short-term rental manager with homes around Surry Hills and Coogee.', published: true },
  { slug: 'urban-stays', name: 'Urban Stays', match: ['urbanstays'], website: null, cities: ['Sydney', 'Melbourne'],
    tagline: 'Short-stay management in Sydney and Melbourne', about: 'Short-term rental manager with homes in Sydney and Melbourne.', published: true },

  // ---------- Melbourne ----------
  { slug: 'property-mums', name: 'Property Mums', match: ['propertymums'], website: 'https://propertymums.com.au', cities: ['Melbourne'],
    tagline: 'Short-term and Airbnb management across Melbourne and coastal Victoria',
    about: 'Melbourne short-term rental manager covering the CBD and inner suburbs, plus the Mornington Peninsula, Bellarine Peninsula, Great Ocean Road and Phillip Island.',
    fee_min: 18, fee_max: 18, fee_note: '18% + GST of rental revenue (published)',
    gated: { setupFee: 650, setupNote: 'A$650 + GST one-time setup (published; their FAQ also mentions A$1,450 + GST onboarding)' },
    sources: ['https://propertymums.com.au/airbnb-management-melbourne/'], published: true },
  { slug: 'bnb-butler', name: 'BnB Butler', match: ['bnbbutler'], website: 'https://bnbbutler.com.au', cities: ['Melbourne'],
    tagline: 'Airbnb management across inner Melbourne',
    about: 'Melbourne short-term rental manager covering the CBD, Southbank, Carlton, Fitzroy, Brunswick, Richmond, South Yarra and Brighton.', sources: ['https://bnbbutler.com.au/services/'], published: true },
  { slug: 'ready-set-stay', name: 'Ready Set Stay', match: ['readysetstay'], website: 'https://readysetstay.com.au', cities: ['Melbourne'],
    tagline: 'Boutique short-stay management, no setup fee or lock-in',
    about: 'Boutique Melbourne short-stay manager covering the inner city, the Mornington Peninsula and Phillip Island. Charges a percentage of nightly income with no setup fee, no lock-in contract and no charge for vacant nights.',
    gated: { setupFee: 0, minTermMonths: 0, setupNote: 'No setup fee, no lock-in contract (published)' },
    sources: ['https://readysetstay.com.au/faq/'], published: true },
  { slug: 'quickstay', name: 'QuickStay', match: ['quickstay'], website: 'https://quickstay.au', cities: ['Melbourne'],
    tagline: 'Short-stay management across Melbourne',
    about: 'Melbourne short-stay property manager covering inner and bayside suburbs, plus the Mornington Peninsula, Phillip Island, Surf Coast and Geelong.', sources: ['https://quickstay.au/airbnb-management-melbourne/'], published: true },
  { slug: 'live-luxe', name: 'Live Luxe', match: ['liveluxemanagement', 'liveluxe'], website: null, cities: ['Melbourne'],
    tagline: 'Styled short-stay management in Melbourne',
    about: 'Melbourne short-stay manager offering a support package and a complete management package.',
    fee_min: 10, fee_max: 18, fee_note: '10% (support) or 18% (complete), as reported', sources: ['https://ensoconnect.com/resources/top-vacation-rental-management-companies-in-australia'], published: true },
  { slug: 'lux-stayz', name: 'Lux Stayz', match: ['luxstayz'], website: null, cities: ['Melbourne'],
    tagline: 'Short-stay management in Melbourne and Southbank', about: 'Short-term rental manager with homes in the Melbourne CBD and Southbank.', published: true },
  { slug: 'vaquay', name: 'VAQUAY', match: ['vaquay'], website: null, cities: ['Melbourne'],
    tagline: 'Boutique, experience-led short-stay management', about: 'Melbourne-based boutique short-term rental manager focused on design-led homes.',
    sources: ['https://ensoconnect.com/resources/top-vacation-rental-management-companies-in-australia'], published: true },
  { slug: 'your-place-your-space', name: 'Your Place Your Space', match: ['yourplaceyourspace'], website: 'https://yourplaceyourspace.com.au', cities: ['Melbourne'],
    tagline: 'Airbnb management in inner and bayside Melbourne',
    about: 'Melbourne short-term rental manager covering Richmond, Carlton, Fitzroy, Southbank, South Yarra, St Kilda, Albert Park and Port Melbourne, plus Hobart.', sources: ['https://yourplaceyourspace.com.au/airbnb-management/'], published: true },
  { slug: 'bedspoke', name: 'Bedspoke', match: ['bedspoke'], website: null, cities: ['Melbourne'],
    tagline: 'Short-stay management in Melbourne', about: 'Melbourne short-term rental manager.', published: true },
  { slug: 'advante-homes', name: 'Advante Homes', match: ['advantehomes'], website: null, cities: ['Melbourne', 'Sydney'],
    tagline: 'Short-stay management in Melbourne and Sydney', about: 'Short-term rental manager with homes in Melbourne and Sydney.', published: true },
  { slug: 'melbourne-furnished-apartments', name: 'Melbourne Furnished Apartments', match: ['furnishedapartments'], website: null, cities: ['Melbourne'],
    tagline: 'Furnished and short-stay apartments in Melbourne', about: 'Operator of furnished and short-stay apartments in Melbourne and St Kilda.', published: true },
  { slug: 'artist-abodes', name: 'Artist Abodes', match: ['hugoartistabodes', 'artistabodes'], website: null, cities: ['Melbourne'],
    tagline: 'High-end homes in Collingwood and Fitzroy', about: 'Boutique manager of high-end short-stay homes in Collingwood and Fitzroy.', published: true },
];
